// constants/efemerides.ts

export const EFEMERIDES: Record<string, string> = {
  // ENERO
  "01-01": "Año Nuevo",
  "01-02": "Día del Trabajador Social",
  "01-03": "Día de las Pajitas (Sorbetes)",
  "01-04": "Día Mundial del Braille",
  "01-05": "Día del Periodista Agropecuario",
  "01-06": "Día de los Reyes Magos",
  "01-07": "Día del Sello Postal",
  "01-08": "Día de la Mujer Tipógrafa",
  "01-09": "Día del Ascenso en Globo",
  "01-10": "Día de los Trabajadores del Transporte",
  "01-11": "Día del Traductor",
  "01-12": "Día del Trabajador Pizzero y Pastelero",
  "01-13": "Día Mundial de la Lucha contra la Depresión",
  "01-14": "Día del Trabajador de la Electricidad",
  "01-15": "Día del Compositor",
  "01-16": "Día Internacional de The Beatles",
  "01-17": "Día de San Antonio Abad (Protector de los Animales)",
  "01-18": "Día de Winnie the Pooh",
  "01-19": "Día del Trabajador Cervecero",
  "01-20": "Día de Concienciación por los Pingüinos",
  "01-21": "Día Internacional del Abrazo",
  "01-22": "Día del Community Manager",
  "01-23": "Día Nacional del Músico (Natalicio de Spinetta)",
  "01-24": "Día Internacional de la Educación",
  "01-25": "Día Nacional del Reportero Gráfico",
  "01-26": "Día Mundial de la Educación Ambiental",
  "01-27": "Día de Conmemoración de las Víctimas del Holocausto",
  "01-28": "Día Internacional de la Privacidad de Datos",
  "01-29": "Día Mundial del Rompecabezas",
  "01-30": "Día Escolar de la No Violencia y la Paz",
  "01-31": "Día Nacional del Mago",

  // FEBRERO
  "02-01": "Día Internacional del Galgo",
  "02-02": "Día Mundial de los Humedales",
  "02-03": "Día Internacional del Abogado",
  "02-04": "Día Mundial contra el Cáncer",
  "02-05": "Día del Trabajador Deportivo",
  "02-06": "Día Internacional de Tolerancia Cero con la Mutilación Genital Femenina",
  "02-07": "Día de mandar una carta a un amigo",
  "02-08": "Día del Trabajador Plástico",
  "02-09": "Día Mundial de la Pizza",
  "02-10": "Día Mundial de las Legumbres",
  "02-11": "Día Internacional de la Mujer y la Niña en la Ciencia",
  "02-12": "Día de Darwin",
  "02-13": "Día Mundial de la Radio",
  "02-14": "Día de San Valentín",
  "02-15": "Día Internacional del Cáncer Infantil",
  "02-16": "Día de los Amores Imposibles",
  "02-17": "Día del Juego Responsable",
  "02-18": "Día Internacional del Síndrome de Asperger",
  "02-19": "Día contra la Homofobia en el Deporte",
  "02-20": "Día Internacional del Camarógrafo y Fotógrafo",
  "02-21": "Día Internacional de la Lengua Materna",
  "02-22": "Día de la Antártida Argentina",
  "02-23": "Día del Tambero",
  "02-24": "Día del Trabajador Mecánico",
  "02-25": "Día Internacional del Implante Coclear",
  "02-26": "Día Mundial del Pistacho",
  "02-27": "Día Internacional del Oso Polar",
  "02-28": "Día Mundial de las Enfermedades Poco Frecuentes",
  "02-29": "Día de las Enfermedades Raras (Año Bisiesto)",

  // MARZO
  "03-01": "Día del Trabajador Ferroviario",
  "03-02": "Día del Escultor",
  "03-03": "Día Mundial de la Vida Silvestre",
  "03-04": "Día Mundial del Tenis",
  "03-05": "Día Nacional del Gas",
  "03-06": "Día del Escultor Argentino (Natalicio de Miguel Ángel)",
  "03-07": "Día del Visibilizador",
  "03-08": "Día Internacional de la Mujer",
  "03-09": "Día Internacional del DJ",
  "03-10": "Día del Guitarrista",
  "03-11": "Día Nacional de la Lucha contra la Violencia de Género en los Medios",
  "03-12": "Día del Escudo Nacional Argentino",
  "03-13": "Día de la Capitalidad de Buenos Aires",
  "03-14": "Día del Trabajador de la Sanidad",
  "03-15": "Día Mundial de los Derechos del Consumidor",
  "03-16": "Día del Ladrillero",
  "03-17": "Día de San Patricio",
  "03-18": "Día del Trabajador Telefónico",
  "03-19": "Día del Carpintero y del Artesano",
  "03-20": "Día Internacional de la Felicidad",
  "03-21": "Día Mundial del Síndrome de Down",
  "03-22": "Día Mundial del Agua",
  "03-23": "Día Meteorológico Mundial",
  "03-24": "Día Nacional de la Memoria por la Verdad y la Justicia",
  "03-25": "Día del Trabajador de Prensa",
  "03-26": "Día Mundial del Clima",
  "03-27": "Día Mundial del Teatro",
  "03-28": "Día Nacional de la Audición",
  "03-29": "Día del Trabajador Portuario",
  "03-30": "Día Mundial del Trastorno Bipolar",
  "03-31": "Día Nacional del Agua",

  // ABRIL
  "04-01": "Día Nacional del Donante de Médula Ósea",
  "04-02": "Día del Veterano y de los Caídos en la Guerra de Malvinas",
  "04-03": "Día del Trabajador Maderero",
  "04-04": "Día Internacional de información sobre el peligro de las minas",
  "04-05": "Día del Instituto Nacional Sanmartiniano",
  "04-06": "Día Internacional del Deporte para el Desarrollo y la Paz",
  "04-07": "Día Mundial de la Salud",
  "04-08": "Día del Trabajador de las Telecomunicaciones",
  "04-09": "Día de la Cardiología Argentina",
  "04-10": "Día del Investigador Científico",
  "04-11": "Día Mundial del Parkinson",
  "04-12": "Día del Decorador y Vidrierista",
  "04-13": "Día Internacional del Beso",
  "04-14": "Día de las Américas",
  "04-15": "Día Mundial del Arte",
  "04-16": "Día Mundial del Emprendimiento",
  "04-17": "Día Mundial del Malbec",
  "04-18": "Día Internacional de los Monumentos y Sitios",
  "04-19": "Día del Aborigen Americano",
  "04-20": "Día Nacional del Voceador (Canillita)",
  "04-21": "Día de la Higiene y Seguridad en el Trabajo",
  "04-22": "Día Internacional de la Madre Tierra",
  "04-23": "Día Mundial del Libro y del Derecho de Autor",
  "04-24": "Día de Acción por la Tolerancia y el Respeto entre los Pueblos",
  "04-25": "Día Mundial del Paludismo",
  "04-26": "Día Internacional de la Propiedad Intelectual",
  "04-27": "Día Internacional del Diseño",
  "04-28": "Día Mundial de la Seguridad y la Salud en el Trabajo",
  "04-29": "Día del Animal",
  "04-30": "Día Internacional del Jazz",

  // MAYO
  "05-01": "Día Internacional del Trabajador",
  "05-02": "Día Internacional contra el Acoso Escolar (Bullying)",
  "05-03": "Día de la Milanesa",
  "05-04": "Día Internacional del Combatiente de Incendios Forestales",
  "05-05": "Día del Enólogo",
  "05-06": "Día del Taxista",
  "05-07": "Día de la Minería",
  "05-08": "Día de la Cruz Roja Internacional",
  "05-09": "Día Internacional de las Aves",
  "05-10": "Día de los Medios de Comunicación",
  "05-11": "Día del Himno Nacional Argentino",
  "05-12": "Día de la Enfermera y el Enfermero",
  "05-13": "Día Nacional del Trabajador de las Telecomunicaciones",
  "05-14": "Día del Dirigente de Fútbol",
  "05-15": "Día del Docente Universitario",
  "05-16": "Día del Trabajador Sanitarista",
  "05-17": "Día de la Armada Argentina",
  "05-18": "Día de la Escarapela Nacional",
  "05-19": "Día del Trabajador de Comercio",
  "05-20": "Día Mundial de las Abejas",
  "05-21": "Día Internacional del Té",
  "05-22": "Día del Pac-Man",
  "05-23": "Día del Cine Nacional",
  "05-24": "Día del Operador de Radio",
  "05-25": "Día de la Revolución de Mayo",
  "05-26": "Día del Agente de Propaganda Médica",
  "05-27": "Día del Marketing",
  "05-28": "Día Internacional de Acción por la Salud de la Mujer",
  "05-29": "Día del Ejército Argentino",
  "05-30": "Día Nacional de la Donación de Órganos",
  "05-31": "Día Nacional del Guía de Turismo",

  // JUNIO
  "06-01": "Día Mundial de la Leche",
  "06-02": "Día Nacional del Bombero Voluntario",
  "06-03": "Día Internacional del Sommelier",
  "06-04": "Día Internacional de los Niños Víctimas Inocentes de Agresión",
  "06-05": "Día Mundial del Medio Ambiente",
  "06-06": "Día de la Ingeniería Argentina",
  "06-07": "Día del Periodista",
  "06-08": "Día Mundial de los Océanos",
  "06-09": "Día del Geólogo",
  "06-10": "Día de la Afirmación de los Derechos Argentinos sobre las Malvinas",
  "06-11": "Día del Vecino",
  "06-12": "Día Mundial contra el Trabajo Infantil",
  "06-13": "Día del Escritor",
  "06-14": "Día Mundial del Donante de Sangre",
  "06-15": "Día del Bioquímico",
  "06-16": "Día del Ingeniero",
  "06-17": "Paso a la Inmortalidad del Gral. Martín Miguel de Güemes",
  "06-18": "Día de la Gastronomía Sostenible",
  "06-19": "Día de la Bandera de Entre Ríos",
  "06-20": "Día de la Bandera Nacional",
  "06-21": "Día del Apicultor",
  "06-22": "Día de los Futbolistas Argentinos",
  "06-23": "Día Olímpico",
  "06-24": "Día del Cantor Nacional (Aniversario muerte de Gardel)",
  "06-25": "Día de la Gente de Mar",
  "06-26": "Día Internacional de la Lucha contra el Uso Indebido y el Tráfico Ilícito de Drogas",
  "06-27": "Día del Trabajador del Estado",
  "06-28": "Día Internacional del Orgullo LGBT",
  "06-29": "Día del Camarógrafo Argentino",
  "06-30": "Día de la Prefectura Naval Argentina",

  // JULIO
  "07-01": "Día del Arquitecto",
  "07-02": "Día del Asistente Social",
  "07-03": "Día del Locutor",
  "07-04": "Día Nacional del Médico Rural",
  "07-05": "Día de la Empleada de Comercio",
  "07-06": "Día Mundial del Pollo Frito",
  "07-07": "Día Nacional de la Conservación del Suelo",
  "07-08": "Día de la Alergia",
  "07-09": "Día de la Independencia de la República Argentina",
  "07-10": "Día del Comerciante",
  "07-11": "Día del Bandoneón",
  "07-12": "Día de la Medicina Social",
  "07-13": "Día del Trabajador de la Energía Eléctrica",
  "07-14": "Día Mundial del Chimpancé",
  "07-15": "Día Mundial de las Habilidades de la Juventud",
  "07-16": "Día de la Virgen del Carmen",
  "07-17": "Día Nacional del Automovilismo Deportivo",
  "07-18": "Día Internacional de Nelson Mandela",
  "07-19": "Día Nacional del Director Técnico de Fútbol",
  "07-20": "Día del Amigo",
  "07-21": "Día Mundial del Perro",
  "07-22": "Día Mundial del Cerebro",
  "07-23": "Día del Payador",
  "07-24": "Día Internacional del Tequila",
  "07-25": "Día de la Mujer Afrolatina",
  "07-26": "Día de los Abuelos",
  "07-27": "Día del Antropólogo",
  "07-28": "Día de la Gendarmería Nacional",
  "07-29": "Día de la Cultura Nacional",
  "07-30": "Día Internacional contra la Trata de Personas",
  "07-31": "Día de la Siderurgia",

  // AGOSTO
  "08-01": "Día de la Pachamama",
  "08-02": "Día del Trabajador Gastronómico",
  "08-03": "Día Internacional de la Planificación Familiar",
  "08-04": "Día del Panadero",
  "08-05": "Día de la Dirección Nacional de Migraciones",
  "08-06": "Día del Ingeniero Agrónomo",
  "08-07": "Día de San Cayetano (Patrono del Pan y del Trabajo)",
  "08-08": "Día Internacional del Gato",
  "08-09": "Día de la Educación Especial",
  "08-10": "Día de la Fuerza Aérea Argentina",
  "08-11": "Día del Nutricionista",
  "08-12": "Día del Trabajador de la Televisión",
  "08-13": "Día del Zurdo",
  "08-14": "Día de la Mujer Policía",
  "08-15": "Día del Relajamiento",
  "08-16": "Día del Abuelo",
  "08-17": "Paso a la Inmortalidad del Gral. José de San Martín",
  "08-18": "Día de la Prevención de Incendios Forestales",
  "08-19": "Día Mundial de la Asistencia Humanitaria",
  "08-20": "Día Mundial de las Papas Fritas",
  "08-21": "Día de la Futbolista Argentina",
  "08-22": "Día Mundial del Folklore",
  "08-23": "Día del Internauta",
  "08-24": "Día del Lector",
  "08-25": "Día del Peluquero",
  "08-26": "Día del Actor",
  "08-27": "Día de la Radiodifusión Argentina",
  "08-28": "Día del Archivero",
  "08-29": "Día del Abogado",
  "08-30": "Día de los Ferrocarriles Argentinos",
  "08-31": "Día de la Obstetricia",

  // SEPTIEMBRE
  "09-01": "Día del Periodista Agropecuario",
  "09-02": "Día de la Industria",
  "09-03": "Día del Ferretero",
  "09-04": "Día de la Secretaria",
  "09-05": "Día del Boy Scout",
  "09-06": "Día de las Relaciones Públicas",
  "09-07": "Día del Trabajador Metalúrgico",
  "09-08": "Día del Agricultor",
  "09-09": "Día del Probador de Software (QA)",
  "09-10": "Día del Terapista Físico",
  "09-11": "Día del Maestro",
  "09-12": "Día de la Industria Naval",
  "09-13": "Día del Bibliotecario",
  "09-14": "Día del Cartero",
  "09-15": "Día Internacional de la Democracia",
  "09-16": "Día de los Derechos de los Estudiantes Secundarios",
  "09-17": "Día del Profesor",
  "09-18": "Día Mundial de la Ética Médica",
  "09-19": "Día del Preceptor",
  "09-20": "Día de los Jubilados",
  "09-21": "Día del Estudiante y de la Primavera",
  "09-22": "Día Mundial sin Automóvil",
  "09-23": "Día de los Derechos Políticos de la Mujer",
  "09-24": "Día del Colectivero",
  "09-25": "Día Mundial del Farmacéutico",
  "09-26": "Día del Empleado de Comercio",
  "09-27": "Día Mundial del Turismo",
  "09-28": "Día del Rector",
  "09-29": "Día del Corazón",
  "09-30": "Día del Traductor",

  // OCTUBRE
  "10-01": "Día Internacional del Café",
  "10-02": "Día del Escribano",
  "10-03": "Día de la Odontología",
  "10-04": "Día Mundial de los Animales",
  "10-05": "Día Mundial de los Docentes",
  "10-06": "Día del Circo",
  "10-07": "Día de la Identidad Villera",
  "10-08": "Día Nacional del Estudiante Solidario",
  "10-09": "Día del Guardaparque",
  "10-10": "Día Nacional de la Danza",
  "10-11": "Día del Árbitro de Fútbol",
  "10-12": "Día del Respeto a la Diversidad Cultural",
  "10-13": "Día del Psicólogo",
  "10-14": "Día Mundial de la Costurera",
  "10-15": "Día Mundial del Lavado de Manos",
  "10-16": "Día Mundial del Pan",
  "10-17": "Día de la Lealtad Peronista",
  "10-18": "Día Mundial de la Menopausia",
  "10-19": "Día Internacional de la Lucha contra el Cáncer de Mama",
  "10-20": "Día del Pediatra",
  "10-21": "Día del Trabajador de Seguros",
  "10-22": "Día Nacional del Derecho a la Identidad",
  "10-23": "Día del Periodista de Aviación",
  "10-24": "Día del Diseño Gráfico",
  "10-25": "Día Mundial de la Pasta",
  "10-26": "Día de la Suegra",
  "10-27": "Día Mundial del Patrimonio Audiovisual",
  "10-28": "Día Mundial de la Animación",
  "10-29": "Día del Aceitero",
  "10-30": "Día de la Recuperación de la Democracia",
  "10-31": "Día Mundial del Ahorro (y Halloween)",

  // NOVIEMBRE
  "11-01": "Día Mundial del Veganismo",
  "11-02": "Día de los Muertos",
  "11-03": "Día del Artista Plástico",
  "11-04": "Día de la UNESCO",
  "11-05": "Día de la Aviación Civil",
  "11-06": "Día de los Parques Nacionales",
  "11-07": "Día del Canillita",
  "11-08": "Día del Trabajador Municipal",
  "11-09": "Día del Inventor",
  "11-10": "Día del Dibujante",
  "11-11": "Día del Soltero",
  "11-12": "Día Mundial contra la Neumonía",
  "11-13": "Día del Pensamiento Nacional",
  "11-14": "Día Mundial de la Diabetes",
  "11-15": "Día de la Educación Técnica",
  "11-16": "Día del Deportista",
  "11-17": "Día Nacional del Escultor",
  "11-18": "Día de los Récords Guinness",
  "11-19": "Día Mundial del Inodoro",
  "11-20": "Día de la Soberanía Nacional",
  "11-21": "Día de la Enfermera en Argentina",
  "11-22": "Día de la Música",
  "11-23": "Día Nacional de la Defensa Civil",
  "11-24": "Día del Vino Argentino",
  "11-25": "Día de la Libertad Religiosa",
  "11-26": "Día del Trabajador No Docente",
  "11-27": "Día del Trabajador Previsional",
  "11-28": "Día de las Amas de Casa",
  "11-29": "Día del Politólogo",
  "11-30": "Día Nacional del Mate",

  // DICIEMBRE
  "12-01": "Día Mundial de la Lucha contra el SIDA",
  "12-02": "Día Internacional para la Abolición de la Esclavitud",
  "12-03": "Día del Médico",
  "12-04": "Día de la Publicidad",
  "12-05": "Día Nacional del Ciclista",
  "12-06": "Día Nacional del Gaucho",
  "12-07": "Día de la Aviación Civil",
  "12-08": "Día de la Inmaculada Concepción",
  "12-09": "Día del Informático",
  "12-10": "Día de la Restauración de la Democracia",
  "12-11": "Día Nacional del Tango",
  "12-12": "Día de la Maquinaria Agrícola",
  "12-13": "Día del Petróleo Nacional",
  "12-14": "Día Mundial del Mono",
  "12-15": "Día del Camionero",
  "12-16": "Día del Óptico",
  "12-17": "Día del Contador",
  "12-18": "Día Internacional del Migrante",
  "12-19": "Día Mundial del Emo",
  "12-20": "Día Internacional de la Solidaridad Humana",
  "12-21": "Día del Gemelo",
  "12-22": "Día del Empleado de Farmacia",
  "12-23": "Día Nacional de la Familia",
  "12-24": "Nochebuena",
  "12-25": "Navidad",
  "12-26": "Día del Empleado de Cajas de Subsidios",
  "12-27": "Día Internacional de la Preparación ante Epidemias",
  "12-28": "Día de los Santos Inocentes",
  "12-29": "Día del Bromatólogo",
  "12-30": "Día del Cineclub",
  "12-31": "Fin de Año",
};

/**
 * Retorna la efeméride del día actual en formato string.
 */
export function getTodayEfemeride(date: Date = new Date()): string {
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  const key = `${month}-${day}`;

  return EFEMERIDES[key] || "Resumen Diario";
}